name: Test Call Customised github action from my own account
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        uses: shenz-sportsbet/hello-world-docker-action@v1
        with:
          who-to-greet: '@shenz'
